name: wireless
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  http: ^0.13.5
  flutter_spinkit: ^5.1.0

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets: 
    - lib/assets/images/chattychat.png
    - lib/assets/images/gpt_ai.png
    - lib/assets/images/logo.jpg
    - lib/assets/images/user.png