name: chattychipsapp
description: Chat Application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.8.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  http: ^1.0.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/images/logo.png
    - lib/images/man.png
    - lib/images/gpt_ai.png

